<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="IN-komehta-W1" failures="16" tests="16" name="BoonSupplyTest" time="2.25" errors="0" timestamp="2019-11-06T19:29:27 IST">
  <testcase classname="boonSupplyTests.AccountTests" name="LoginToBoonSupply" time="0.035">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.AccountTests.LoginToBoonSupply(AccountTests.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- LoginToBoonSupply -->
  <testcase classname="boonSupplyTests.AccountTests" name="LoginToBoonSupply" time="0.019">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.AccountTests.LoginToBoonSupply(AccountTests.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- LoginToBoonSupply -->
  <testcase classname="boonSupplyTests.AccountTests" name="CreateNewAccount" time="0.011">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.AccountTests.CreateNewAccount(AccountTests.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- CreateNewAccount -->
  <testcase classname="boonSupplyTests.AccountTests" name="UpdateAccountInformation" time="0.003">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.AccountTests.UpdateAccountInformation(AccountTests.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- UpdateAccountInformation -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.007">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.003">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.01">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.008">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.012">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.007">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.009">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.016">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.011">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.022">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="GetFeaturedFundRaisers" time="0.002">
    <failure type="java.lang.AssertionError" message="There is an Exception.Please check the functionality.">
      <![CDATA[java.lang.AssertionError: There is an Exception.Please check the functionality.
at boonSupplyTests.SearchFundraiserTest.GetFeaturedFundRaisers(SearchFundraiserTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- GetFeaturedFundRaisers -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="GetTrendingItemsforShopping" time="0.008">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality manually.
at boonSupplyTests.ShopforItemsTest.GetTrendingItemsforShopping(ShopforItemsTest.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- GetTrendingItemsforShopping -->
  <testcase classname="boonSupplyTests.CreateFundraiserTest" name="StartNewFundRaiserWithNewUser" time="0.0">
    <ignored/>
  </testcase> <!-- StartNewFundRaiserWithNewUser -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="AddA25DollarItemInCart" time="0.0">
    <ignored/>
  </testcase> <!-- AddA25DollarItemInCart -->
  <testcase classname="boonSupplyTests.ClosingAndCancellingTests" name="CloseFundRaiser" time="0.0">
    <ignored/>
  </testcase> <!-- CloseFundRaiser -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="ValidateCheckoutPageFeatures" time="0.0">
    <ignored/>
  </testcase> <!-- ValidateCheckoutPageFeatures -->
  <testcase classname="boonSupplyTests.ShopforItemsTest" name="AddMultipleItemsInCart" time="0.0">
    <ignored/>
  </testcase> <!-- AddMultipleItemsInCart -->
  <testcase classname="boonSupplyTests.ClosingAndCancellingTests" name="CancelMyAccount" time="0.0">
    <ignored/>
  </testcase> <!-- CancelMyAccount -->
</testsuite> <!-- BoonSupplyTest -->
