<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-komehta-W1" failures="11" tests="11" name="SearchFundraiserTest" time="0.734" errors="0" timestamp="2019-11-06T20:13:59 IST">
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.009">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.037">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.033">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.071">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="SearchAFundraiser" time="0.009">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.SearchAFundraiser(SearchFundraiserTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SearchAFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.005">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.014">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.019">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.013">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="getTheNumberOfFundraiser" time="0.006">
    <failure type="java.lang.AssertionError" message="There is an Exception. Please check the functionality Manually.">
      <![CDATA[java.lang.AssertionError: There is an Exception. Please check the functionality Manually.
at boonSupplyTests.SearchFundraiserTest.getTheNumberOfFundraiser(SearchFundraiserTest.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getTheNumberOfFundraiser -->
  <testcase classname="boonSupplyTests.SearchFundraiserTest" name="GetFeaturedFundRaisers" time="0.016">
    <failure type="java.lang.AssertionError" message="There is an Exception.Please check the functionality.">
      <![CDATA[java.lang.AssertionError: There is an Exception.Please check the functionality.
at boonSupplyTests.SearchFundraiserTest.GetFeaturedFundRaisers(SearchFundraiserTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- GetFeaturedFundRaisers -->
</testsuite> <!-- SearchFundraiserTest -->
