<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-komehta-W1" failures="2" tests="18" name="boonSupplyTests.BoonSupplyTests" time="667.473" errors="0" timestamp="2019-10-29T23:56:08 IST" skipped="0">
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="SearchAFundraiser" time="24.506"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="AddA25DollarItemInCart" time="25.962"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="AddMultipleItemsInCart" time="29.432"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="LoginToBoonSupply" time="22.574"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CreateNewAccount" time="26.999"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="UpdateAccountInformation" time="29.710"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="58.856"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="40.399"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="40.686"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="43.430"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="44.415"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="30.238">
    <failure message="User Does not Exist in the System." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User Does not Exist in the System.
at org.testng.Assert.fail(Assert.java:97)
at boonSupplyPage.LoggedInUserPage.existingUserSignIn(LoggedInUserPage.java:35)
at boonSupplyTests.BoonSupplyTests.CloseFundRaiser(BoonSupplyTests.java:243)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CloseFundRaiser -->
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="47.722"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="45.196"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="40.545"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="44.780"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="29.411">
    <failure message="User Does not Exist in the System." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User Does not Exist in the System.
at org.testng.Assert.fail(Assert.java:97)
at boonSupplyPage.LoggedInUserPage.existingUserSignIn(LoggedInUserPage.java:35)
at boonSupplyTests.BoonSupplyTests.CancelMyAccount(BoonSupplyTests.java:270)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CancelMyAccount -->
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="42.612"/>
</testsuite> <!-- boonSupplyTests.BoonSupplyTests -->
