<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-komehta-W1" failures="2" tests="19" name="boonSupplyTests.BoonSupplyTests" time="850.116" errors="0" timestamp="2019-10-30T23:04:24 IST" skipped="0">
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="SearchAFundraiser" time="26.170"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="AddA25DollarItemInCart" time="40.306"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="AddMultipleItemsInCart" time="28.144"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="LoginToBoonSupply" time="24.615"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="LoginToBoonSupply" time="20.612"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CreateNewAccount" time="29.463"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="UpdateAccountInformation" time="35.659"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="49.945"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="53.747"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="60.656"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="StartNewFundRaiserWithNewUser" time="64.681"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="49.074"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="64.395"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="70.767"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CloseFundRaiser" time="37.981">
    <failure message="User Does not Exist in the System." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User Does not Exist in the System.
at org.testng.Assert.fail(Assert.java:97)
at boonSupplyPage.LoggedInUserPage.existingUserSignIn(LoggedInUserPage.java:35)
at boonSupplyTests.BoonSupplyTests.CloseFundRaiser(BoonSupplyTests.java:248)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CloseFundRaiser -->
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="43.989"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="50.208"/>
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="54.034">
    <failure message="User Does not Exist in the System." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User Does not Exist in the System.
at org.testng.Assert.fail(Assert.java:97)
at boonSupplyPage.LoggedInUserPage.existingUserSignIn(LoggedInUserPage.java:35)
at boonSupplyTests.BoonSupplyTests.CancelMyAccount(BoonSupplyTests.java:277)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CancelMyAccount -->
  <testcase classname="boonSupplyTests.BoonSupplyTests" name="CancelMyAccount" time="45.670"/>
</testsuite> <!-- boonSupplyTests.BoonSupplyTests -->
